const Keys = {
  CLEAR_CONTACT: 'CLEAR_CONTACT',
  LOAD_CONTACT: 'LOAD_CONTACT',
  SET_SENDING: 'SET_SENDING',
  EDIT_CONTACT_US_ON: 'EDIT_CONTACT_US_ON',
  EDIT_CONTACT_US_OFF: 'EDIT_CONTACT_US_OFF'
};

export default Keys;
