const Keys = {
  SET_APP_READY: 'SET_APP_READY',
  CLEAR_APP_READY: 'CLEAR_APP_READY',
  LOAD_APP_CONFIG: 'LOAD_APP_CONFIG',
  SHOW_AUTH: 'SHOW_AUTH',
  SHOW_AUTH_ERROR: 'SHOW_AUTH_ERROR',
  SET_IS_ADMIN: 'SET_IS_ADMIN',
  SHOW_HEADER: 'SHOW_HEADER'
};

export default Keys;
