const Keys = {
  SET_APP_READY: 'SET_APP_READY',
  CLEAR_APP_READY: 'CLEAR_APP_READY',
  LOAD_APP_CONFIG: 'LOAD_APP_CONFIG',
  SHOW_AUTH: 'SHOW_AUTH',
  SET_IS_ADMIN: 'SET_IS_ADMIN'
};

export default Keys;
